In [2]:
import os
import time
#  
import numpy as np
import random
from milvus import Milvus,MetricType, IndexType
SERVER_ADDR = '127.0.0.1'
SERVER_PORT = '19530'

In [3]:
milvus = Milvus(host=SERVER_ADDR, port=SERVER_PORT)
# create_milvus_collection(milvus)

In [4]:
#  ➜ sudo docker run -d --name milvus_cpu_1.1.0 \
# -p 19530:19530 \
# -p 19121:19121 \
# -v /home/$USER/milvus/db:/var/lib/milvus/db \
# -v /home/$USER/milvus/conf:/var/lib/milvus/conf \
# -v /home/$USER/milvus/logs:/var/lib/milvus/logs \
# -v /home/$USER/milvus/wal:/var/lib/milvus/wal \
# milvusdb/milvus:1.1.0-cpu-d050721-5e559c

In [5]:
host = '127.0.0.1'
port = '19530'
client = Milvus(host, port)

In [6]:
client.list_collections()

(Status(code=0, message='Show collections successfully!'), [])

In [7]:
collection_name = 'demo_film_tutorial'
collection_param = {
    "collection_name": collection_name,
    "dimension": 8,
    "index_file_size": 2048,
    "metric_type": MetricType.L2
}
client.create_collection(collection_param)

Status(code=0, message='Create collection successfully!')

In [ ]:
client.list_collections()

In [ ]:
client.list_partitions(collection_name)

In [ ]:
client.create_partition(collection_name, "films")

In [ ]:
import random

In [ ]:
film_A = [random.random() for _ in range(8)]

In [ ]:
film_A

In [ ]:
entity_ids = [0, 1, 2]
entities = [[random.random() for _ in range(8)] for _ in range(3)]
status, ids = client.insert(collection_name, entities, entity_ids)

In [ ]:
status, results = client.search(collection_name, 2, [film_A])

In [ ]:
results

In [ ]:
ids

In [ ]:
client.create_index(collection_name, IndexType.FLAT)

In [ ]:
query_vectors = film_A

In [ ]:
query_vectors = [[1,2,3,4,5,6,7,8]]

In [ ]:
# FLAT
client.search(collection_name,1,query_vectors)

In [ ]:
status, info = client.get_collection_info(collection_name)

In [ ]:
info

In [ ]:
status, results = client.search(collection_name, 2, [film_A])

In [ ]:
status

In [ ]:
results

In [8]:
from bohb import *

In [9]:
from bohb import BOHB
import bohb.configspace as cs


def objective(step, alpha, beta):
    return 1 / (alpha * step + 0.1) + beta


def evaluate(params, n_iterations):
    loss = 0.0
    for i in range(int(n_iterations)):
        loss += objective(**params, step=i)
    return loss/n_iterations


alpha = cs.CategoricalHyperparameter('alpha', [0.001, 0.01, 0.1])
beta = cs.CategoricalHyperparameter('beta', [1, 2, 3])
configspace = cs.ConfigurationSpace([alpha, beta], seed=123)

opt = BOHB(configspace, evaluate, max_budget=10, min_budget=1)
logs = opt.optimize()
print(logs)


s_max: 3
s: 0
Budget: 10
Loss: 10.187714031754279
Configuration:
   Name: alpha | Value: 0.01
   Name: beta  | Value: 3

s: 1
Budget: 3.333333333333333
Loss: 7.111111111111111
Configuration:
   Name: alpha | Value: 0.1
   Name: beta  | Value: 1

Budget: 10.0
Loss: 3.9289682539682547
Configuration:
   Name: alpha | Value: 0.1
   Name: beta  | Value: 1

s: 2
Budget: 1.1111111111111112
Loss: 11.0
Configuration:
   Name: alpha | Value: 0.01
   Name: beta  | Value: 1

Budget: 3.3333333333333335
Loss: 7.111111111111111
Configuration:
   Name: alpha | Value: 0.1
   Name: beta  | Value: 1

Budget: 10.0
Loss: 3.9289682539682547
Configuration:
   Name: alpha | Value: 0.1
   Name: beta  | Value: 1

Best Hyperparameter Configuration:
Budget: 10.0
Loss: 3.9289682539682547
Configuration:
   Name: alpha | Value: 0.1
   Name: beta  | Value: 1



In [12]:
!pwd

/home/xiangpan/Labs/HOBO


In [91]:
import numpy as np
fv = numpy.fromfile("./cached_datasets/siftsmall/siftsmall_base.fvecs", dtype="int32")
dim = fv.view(numpy.int32)[0]
new = fv.reshape(-1, dim + 1)[:,1:] # reshapes file
f_new = new.view(numpy.float32)
np.save("./cached_datasets/siftsmall_numpy/siftsmall_base",f_new)

In [93]:
f_new

array([[ 0., 16., 35., ..., 25., 23.,  1.],
       [14., 35., 19., ..., 11., 21., 33.],
       [ 0.,  1.,  5., ...,  4., 23., 10.],
       ...,
       [48.,  1.,  0., ..., 22., 62., 18.],
       [ 0.,  0.,  0., ...,  3.,  3., 11.],
       [14.,  2.,  0., ...,  0.,  0.,  7.]], dtype=float32)

In [70]:
import numpy as np
fv = numpy.fromfile("./cached_datasets/siftsmall/siftsmall_groundtruth.ivecs", dtype="int32")
# dim = fv.view(numpy.int32)[0]
dim = 100
f_new = fv.reshape(-1, dim + 1)[:,1:] # reshapes file
# f_new = new.view(numpy.float32)
np.save("./cached_datasets/siftsmall_numpy/siftsmall_groundtruth",f_new)

In [60]:
fv = numpy.fromfile("./cached_datasets/siftsmall/siftsmall_groundtruth.ivecs", dtype="int32")

In [71]:
new

array([[2176, 3752,  882, ...,  348, 3043, 3687],
       [2781, 9574, 2492, ..., 3849, 2905, 4102],
       [2707, 9938, 2698, ..., 1251, 8564, 8173],
       ...,
       [8825, 9081, 6142, ..., 8178, 5887, 4565],
       [5460, 5439, 5810, ..., 5199, 7483, 5232],
       [8082, 8782, 4767, ...,   11, 2482, 3631]], dtype=int32)

In [29]:
import numpy as np
fv = numpy.fromfile("./cached_datasets/siftsmall/siftsmall_learn.fvecs", dtype="int32")
dim = fv.view(numpy.int32)[0]
new = fv.reshape(-1, dim + 1)[:,1:] # reshapes file
f_new = new.view(numpy.float32)
np.save("./cached_datasets/siftsmall_numpy/siftsmall_learn",f_new)

In [94]:
import numpy as np
fv = numpy.fromfile("./cached_datasets/siftsmall/siftsmall_query.fvecs", dtype="int32")
dim = fv.view(numpy.int32)[0]
new = fv.reshape(-1, dim + 1)[:,1:] # reshapes file
f_new = new.view(numpy.float32)
np.save("./cached_datasets/siftsmall_numpy/siftsmall_query",f_new)

In [96]:
f_new

array([[ 1.,  3., 11., ..., 42., 48., 11.],
       [40., 25., 11., ...,  3., 19., 13.],
       [28.,  4.,  3., ...,  2., 54., 47.],
       ...,
       [14.,  8.,  0., ..., 32., 14., 15.],
       [11., 48., 10., ...,  0.,  0.,  0.],
       [ 4., 10.,  5., ..., 43.,  0.,  8.]], dtype=float32)

In [72]:
docker

NameError: name 'docker' is not defined

# Connection

In [76]:
import os
import time
#  
import numpy as np
import random
from milvus import Milvus,MetricType, IndexType
SERVER_ADDR = '127.0.0.1'
SERVER_PORT = '19530'

host = '127.0.0.1'
port = '19530'
client = Milvus(host, port)

In [77]:
collection_name = 'siftsmall'
collection_param = {
    "collection_name": collection_name,
    "dimension": 128,
#     "index_file_size": 2048,
    "metric_type": MetricType.L2
}
client.create_collection(collection_param)

Status(code=0, message='Create collection successfully!')

In [78]:
client.list_collections()

(Status(code=0, message='Show collections successfully!'),
 ['demo_film_tutorial', 'siftsmall'])

# insert base into db

In [231]:
siftsmall_base = np.load("./cached_datasets/siftsmall_numpy/siftsmall_base.npy")

In [232]:
siftsmall_base.shape

(10000, 128)

In [233]:
entity_ids = [i for i in range(len(siftsmall_base))]
entities = siftsmall_base

In [234]:
status, ids = client.insert(collection_name, entities, entity_ids)

# index build

In [246]:
client.create_index(collection_name, IndexType.IVF_FLAT, {"nlist": 100})
# int. 1~65536

Status(code=0, message='Build index successfully!')

# search query

## get_query 

In [263]:
siftsmall_query = np.load("./cached_datasets/siftsmall_numpy/siftsmall_query.npy")
query_vectors = siftsmall_query

In [264]:
statue, res = client.search(collection_name, top_k = 100, query_records = query_vectors, params={"nprobe": 1 })
# int. 1~nlist(cpu), 1~min[2048, nlist](gpu)

In [265]:
res.shape

(100, 100)

## result_convert

In [266]:
converted_res = np.zeros(res.shape)

In [267]:
for i in range(len(res)):
    for j in range(len(res[i])):
#         print(i,j,res[i][j].id)
        converted_res[i][j] = res[i][j].id

## get_groundtruth

In [268]:
siftsmall_groundtruth = np.load("./cached_datasets/siftsmall_numpy/siftsmall_groundtruth.npy")
siftsmall_groundtruth.shape
# query_vectors = siftsmall_query

(100, 100)

In [269]:
converted_res.shape

(100, 100)

# recall

In [254]:
from torchmetrics import RetrievalRecall
# import torch.tensor as tensor
indexes = torch.tensor([0, 0, 0, 1, 1, 1, 1])
preds = torch.tensor([0.2, 0.3, 0.5, 0.1, 0.3, 0.5, 0.2])
target = torch.tensor([False, False, True, False, True, False, True])
r2 = RetrievalRecall(k=100)
r2(preds, target, indexes=indexes)


tensor(1.)

In [270]:
preds = converted_res

In [271]:
target = siftsmall_groundtruth

In [272]:
preds

array([[2176., 3752.,  882., ..., 1699.,  270.,  479.],
       [3136., 1038., 3998., ..., 1401., 6138., 3289.],
       [2707., 6801., 5171., ..., 6065., 2876., 6909.],
       ...,
       [6142., 6234., 7467., ...,    0.,    0.,    0.],
       [5460., 5439., 5810., ..., 7876., 6354., 5360.],
       [8082., 8782., 4767., ...,    0.,    0.,    0.]])

In [279]:
recall_total

34.26